credentials:
  usernames:
    sajith:
      email: sajith.kp.2002@gmail.com
      name: sajith kuttipuravan
      password: $2b$12$KIl30bCL2bByW5XmE8CmM.a6U88tuCJGx6ZmD9WE5kyaFd/hMraOu # To be replaced with hashed password
    jyothish:
      email: jyothish.i.2003@gmail.com
      name: jyothish inklampurath
      password: $2b$12$BdUiSqMU4o/pT0Rhthnnt.lYuAX.7MkDTC9OkmY3WlQQsMdAIBEF2 # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com